### ISSUE TITLE
Cheapest electricity hours -sensor not toggling correctly when failsafe is set just after last_hour

### ISSUE THREAD

**Issue by teelahti** [kotope/aio_energy_management#33]
I used the old script-based approach for a long time without issues, but now AIO based one has a new, weird bug: The cheapest hours sensor does not turn to "on" correctly. 

Here's my setup:

<img width="548" alt="Screenshot 2024-10-21 at 9 26 59" src="https://github.com/user-attachments/assets/8f1426d4-18cc-422c-b160-482f8a285055">

Here's the sensor information and attributes. As seen, the sensor did not correctly turn on. Failsafe is not on either. 

<img width="545" alt="Screenshot 2024-10-21 at 8 50 29" src="https://github.com/user-attachments/assets/2ed548a8-3686-429c-b067-14dd30d6d45d">

What's even weirder is that the calendar shows correct data; cheapest hours should have started at 01.00. 

<img width="448" alt="Screenshot 2024-10-21 at 8 50 49" src="https://github.com/user-attachments/assets/c0bb3cea-3820-4563-9138-f95966ce68da">

Based on the above I feel like there is some kind of bug in the current logic, but I'm out of ideas how to debug this further.

**Comment by kotope** [comment]
Few basic questions again:
 - Are you running the latest version of AIO Energy Management (0.3.0) ?
 - Have you restarted Home Assistant yesterday?
 
 Just asking these as there were similar problems earlier with 0.2.x version that should be fixed now.

**Comment by teelahti** [comment]
Running the latest; I had the issue with restart previously. Restarted day before yesterday, and this toggling issue has happened twice since. As I did not restart yesterday I assumed it is not related to same problem (but I might be wrong).

Looking at my own screenshots I noticed now that the cheapest times list in the sensor is correct, the main state just doesn't change correctly.

**Comment by kotope** [comment]
Thanks for the info. It's indeed odd that the binary sensor status is wrong, but attributes seems to be fine.

There's few things that can get wrong on that point: 
 - Getting the attributes. Seems unlikely as the data is shown is correct, but in theory, if during night local data has been invalid it will return false. Failsafe should in trigger on that point though
  - Date conversions fail.
  
So, a followup questions:
 - What locale are you using on your Home Assistant? 
 - You said it has happened twice, is it constant every night or is it 'random' or have you noticed any pattern on the timeframe that it's reproducing? 
 
Anyhow I agree that there's probably some bug on the code now caused with some specific config or setting. I haven't noticed it on my dev or prod env at all and I've got quite bunch of different configurations running.

Ps. your first_hour is 00 even though it should be 0. Should not matter though, but I'd suggest of changing that just to make sure.

**Comment by teelahti** [comment]
My home assistant locale is en-GB. 

This has now happened on two consecutive nights after the last restart. So I don't know whether it is random, or started to happen consistently after the restart. It used to work before, and I didn't change any of AIO settings. That's why I'm puzzled.

I changed the first hour, thanks for noticing!

**Comment by kotope** [comment]
I'll make a similar config to my dev env to see if I can reproduce the issue.

Please report here if you keep experiencing the same issue again.

Ps. You need to restart Home Assistant after 00 -> 0 change for it to be effective.

**Comment by kotope** [comment]
That's very odd behaviour indeed as everything seem to work with me using exact same configurations.

Could enable debug logging for AIO Energy Management and send me the logs during after upcoming night has been passed? I most probably can figure out the reason by checking the logs when the binary sensor should turn on.

**Comment by teelahti** [comment]
Debug logging enabled, I'll collect them after the issue reproduces the next time.

**Comment by teelahti** [comment]
Luckily for us, the problem continued. Here's again the screenshot of the situation; should have turned on (or rather stay on) at midnight, but did not. 
<img width="533" alt="Screenshot 2024-10-23 at 8 06 26" src="https://github.com/user-attachments/assets/8723fd0d-bf33-4b2c-80af-01c7ce0065e4">

And here are all the logs since midnight (i.e. UTC 21:00):

```log
2024-10-22 20:57:00.687 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Local entity data is still valid for cheapest_electricity_hours
2024-10-22 20:57:30.688 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Local entity data is still valid for cheapest_electricity_hours
2024-10-22 20:58:00.689 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Local entity data is still valid for cheapest_electricity_hours
2024-10-22 20:58:30.690 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Local entity data is still valid for cheapest_electricity_hours
2024-10-22 20:59:00.691 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Local entity data is still valid for cheapest_electricity_hours
2024-10-22 20:59:30.691 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Local entity data is still valid for cheapest_electricity_hours
2024-10-23 05:00:01.625 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No today fetch done for cheapest_electricity_hours or value is expired. Request new data from nord pool integration
2024-10-23 05:00:01.626 DEBUG (MainThread) [custom_components.aio_energy_management.coordinator] Request to save data: {'cheapest_electricity_hours': {'active_number_of_hours': 8, 'failsafe': {'start': datetime.time(0, 0), 'end': datetime.time(8, 0)}, 'expiration': datetime.datetime(2024, 10, 24, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'updated_at': datetime.datetime(2024, 10, 23, 8, 0, 1, 626290, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'fetch_date': datetime.date(2024, 10, 22), 'name': 'Cheapest electricity hours', 'type': 'CheapestHoursBinarySensor', 'list': [{'start': datetime.datetime(2024, 10, 23, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 23, 1, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}, {'start': datetime.datetime(2024, 10, 23, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 23, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}, {'start': datetime.datetime(2024, 10, 23, 14, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 23, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}, {'start': datetime.datetime(2024, 10, 23, 23, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 24, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}]}}
2024-10-23 05:00:01.632 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255 
2024-10-23 05:00:01.632 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Could not get the latest data from nordpool integration
2024-10-23 05:00:31.627 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No today fetch done for cheapest_electricity_hours or value is expired. Request new data from nord pool integration
2024-10-23 05:00:31.627 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255 
2024-10-23 05:00:31.627 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Could not get the latest data from nordpool integration
2024-10-23 05:01:01.627 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No today fetch done for cheapest_electricity_hours or value is expired. Request new data from nord pool integration
2024-10-23 05:01:01.628 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255 
2024-10-23 05:01:01.628 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Could not get the latest data from nordpool integration
2024-10-23 05:01:31.628 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No today fetch done for cheapest_electricity_hours or value is expired. Request new data from nord pool integration

```

**Comment by kotope** [comment]
Is that really all? If so, my guess would be that there's most likely something broken with your Home Assistant itself.
The main loop should run about every 30s (called by Home Assistant), but as you see in your logs there are nothing between 21.00-05.00

Please ensure that there are no automations running that will disable certain integrations or tasks between that specified time frame. 

If you check the full logs from other components as well, do you see any activity between that timeframe?

**Comment by teelahti** [comment]
I downloaded full logs, and removed everything (mostly AIO debug) before 21:00, and removed four (typical) lines of Chromecast connection dropping. That's all there is. I was surprised also to see AIO stop writing to logs during 21-05, too.

Zero automations ran during that timeframe, and I don't even have automations that would disable integrations.

**Comment by teelahti** [comment]
Grepped all my config, and that cheapest hours sensor is only used in its own definition, and in heating automation:

```text
ha-config  master
❯ rg cheapest
configuration.yaml
64:    cheapest_hours:
66:        unique_id: cheapest_electricity_hours

automations.yaml
116:    - binary_sensor.cheapest_electricity_hours
132:    - binary_sensor.cheapest_electricity_hours
```

This is definitely puzzling. I'll reboot the whole box this evening, and try to google causes to stop all timers in HA later today.

**Comment by teelahti** [comment]
FYI: Rebooting the whole system did nothing. Same symptoms continued: Cheapest hours toggle worked 23:00, but failed at 01:00. Debug logging stopped again at midnight (i.e. 21:00 local). During the time AIO stays shut HA works normally: automations like motion sensor lights work as intended. 

I just added another sensor with same settings and different ID to see if there is something corrupt with that exact entity. Let's see if that gives more information what's going on.

**Comment by kotope** [comment]
Thanks for update!

So far I have zero ideas where the problem could be as I've never experienced anything that the integration stops working during certain time of day, continuously.

I'll try to dig through Home Assistant integration guidelines more throughly and google later today if I can find something out as well.

On what system are you running your Home Assistant? Just a wild idea that if there's some memory protection in place that will automatically stop integration(s) if resources are low.

**Comment by kotope** [comment]
Yup, you should get another log line when is_fetched_today fails or not.

If you are even a bit familiar with coding, you could add a debug line in the first lines of these functions:

[async_update](https://github.com/kotope/aio_energy_management/blob/main/custom_components/aio_energy_management/cheapest_hours_binary_sensor.py#L77)

[is_on](https://github.com/kotope/aio_energy_management/blob/main/custom_components/aio_energy_management/cheapest_hours_binary_sensor.py#L87)

Those methods should be called about every 30s by Home Assistant core. If log is not written, then there's something wrong in HA itself (or of course possible of some initialization data missing  that I'm not aware of).

**Comment by teelahti** [comment]
Good idea, I'll add logging there. (and yes, I know my way around in code :-))

**Comment by teelahti** [comment]
Ok, we finally got more information. I now have two identical cheapest hours sensors like the screenshotted one in the first post of this issue. The only difference is that the other one's ID has suffix "2". 

This is how they behave: the original is still defunct, the new one works as expected. 

<img width="568" alt="Screenshot 2024-10-25 at 8 00 23" src="https://github.com/user-attachments/assets/21bb1b9c-104c-46d8-9efd-2bd89a01c58f">
<img width="568" alt="Screenshot 2024-10-25 at 8 00 36" src="https://github.com/user-attachments/assets/ebbd4719-107a-41ab-81ff-16096f35e299">

As seen from the screenshot, toggle to on should have happened at 00:02.29. This time there are proper logs throughout the night. Logs around that time (i.e. 23:00 UTC), grouping component name removed from all lines for clarity:

```text
2024-10-24 23:00:29.011 DEBUG (MainThread) [...] async_update called for cheapest_electricity_hours
2024-10-24 23:00:29.012 DEBUG (MainThread) [...] is_on called for cheapest_electricity_hours
2024-10-24 23:00:29.012 DEBUG (MainThread) [...] async_update called for cheapest_electricity_hours2
2024-10-24 23:00:29.013 DEBUG (MainThread) [...] No today fetch done for cheapest_electricity_hours2 or value is expired. Request new data from nord pool integration
2024-10-24 23:00:29.013 DEBUG (MainThread) [...] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255 
2024-10-24 23:00:29.013 DEBUG (MainThread) [...] Could not get the latest data from nordpool integration
2024-10-24 23:00:29.014 DEBUG (MainThread) [...] is_on called for cheapest_electricity_hours2
2024-10-24 23:00:59.012 DEBUG (MainThread) [...] async_update called for cheapest_electricity_hours
2024-10-24 23:00:59.013 DEBUG (MainThread) [...] is_on called for cheapest_electricity_hours
2024-10-24 23:00:59.014 DEBUG (MainThread) [...] async_update called for cheapest_electricity_hours2
2024-10-24 23:00:59.014 DEBUG (MainThread) [...] No today fetch done for cheapest_electricity_hours2 or value is expired. Request new data from nord pool integration
2024-10-24 23:00:59.014 DEBUG (MainThread) [...] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255 
2024-10-24 23:00:59.015 DEBUG (MainThread) [...] Could not get the latest data from nordpool integration
2024-10-24 23:00:59.015 DEBUG (MainThread) [...] is_on called for cheapest_electricity_hours2
```

My additional debug calls are included. The main difference between the original and new sensor is that the original never goes deeper into the logic, i.e. "No today fetch done..." is missing from the original. Also, there's no debug logging for the change in the sensor state. 

The logic: https://github.com/kotope/aio_energy_management/blob/4b7ddf842e96a645740096d21c96d210f9c85828/custom_components/aio_energy_management/cheapest_hours_binary_sensor.py#L114-L138

Reading that it is evident the flow difference happens since fail safe is now on, which is also seen from the above screenshots. Fail safe was not on during previous nights. The unknowns: 

- Would the original sensor have now worked if fail safe was off? 
- Why did the sensor never recover from fail safe mode?

Hope this helps finding the bug if there is one. If this still seems like a HA bug, I'll just switch my heating automation to the new copied sensor, family gets warm showers again, and I'll forget any of this ever happened 😆.

**Comment by teelahti** [comment]
The joy was premature: the copied sensor didn't survive the second night. It regressed to fail just like the original one: doesn't work after midnight. I'll go through the logic in detail to try to find a possibility to "deadlock" like this.

**Comment by kotope** [comment]
Sorry I've not been able read your reports yesterday, but seems like the issue still persists.

If you still have your custom debug log lines running, did you get those is_on and async_update log events after midnight?

**Comment by kotope** [comment]
Went through your logs from yesterday and checked the code a bit regarding that..

In theory, if _'self._data'_ is lost during midnight we still get those _async_update_ and _is_on_ updates, but nothing else. 
And as your time frame is a full day, the data swap between list and list_next is done at that point. 

..and as we go forward to the data swap, if list_next is missing the list is popped out of the the new list will be missing. 
So most probably reason for this is now that the list_next is not set up correctly when getting new next day prices.

Could you check today after new prices are published if you get the list_next attribute visible on the sensor?

**Comment by kotope** [comment]
Could be that this comparing previous list to cheapest 'fails', giving the same result and thus not creating the list_next attribute correctly. (Line 219 to be exact). 

https://github.com/kotope/aio_energy_management/blob/4b7ddf842e96a645740096d21c96d210f9c85828/custom_components/aio_energy_management/cheapest_hours_binary_sensor.py#L216-L220

**Comment by smurfb** [comment]
I actually have the same problem. My sensors are working great during day time, but around midnight there are problems. I thought it might be connected to timezones.

**Comment by teelahti** [comment]
> If you still have your custom debug log lines running, did you get those is_on and async_update log events after midnight?

Sorry, I already disabled them as I was happy my copied sensor works. I'm happy to enable and add logging if it helps. 

Also glad to see @smurfb also has this issue, it reduces  the risk my HA is corrupt 😮‍💨.

**Comment by kotope** [comment]
@teelahti would you mind changing your configuration to run from 23-23 (start_time 23, end_time 22) and starting_today as true.

Would like to see if everything works fine on that configuration. If it works, you could use it as a workaround until the issue is found and fixed.
I've got a hunch where the problem could lie and I'm currently trying to reproduce it with unit tests, but no luck yet.

**Comment by kotope** [comment]
The problem most probably lies in within Nord Pool data update.

If event loop is run for AIO Energy Management integration before Nord Pool Integration, we get invalid data for AIO Energy Management as we rely on tomorrow_valid flag.
As if the Nord Pool is not run yet, tomorrow_valid will be still true even if already running on new day and data gets 'lost'. This kind of explains why it's not producing on my env. I just happen to get the event loop for AIO Energy Management before Nord Pool.

**Comment by kotope** [comment]
Fix proposal now in on dev branch.

@teelahti if you have a change, could you test the dev branch on your env to see if the issue still reproduces? You can install the dev branch manually by ssh'ing into Home Assistant (I'm quite certain you already know this stuff though..)

Here's commands to run on custom_components folder to get the dev branch installed:

git clone -b dev https://github.com/kotope/aio_energy_management aio_energy_management_git
mv aio_energy_management_git/custom_components/aio_energy_management .
rm -rf aio_energy_management_git

**Comment by teelahti** [comment]
> If event loop is run for AIO Energy Management integration before Nord Pool Integration, we get invalid data for AIO Energy Management as we rely on tomorrow_valid flag. As if the Nord Pool is not run yet, tomorrow_valid will be still true even if already running on new day and data gets 'lost'. This kind of explains why it's not producing on my env. I just happen to get the event loop for AIO Energy Management before Nord Pool.

This sounds plausible and would explain why it is installation specific. Cood catch.

**Comment by teelahti** [comment]
> @teelahti if you have a change, could you test the dev branch on your env to see if the issue still reproduces? You can install the dev branch manually by ssh'ing into Home Assistant (I'm quite certain you already know this stuff though..)

Done, and HA restarted after. I'll report back tomorrow.

**Comment by kotope** [comment]
> > @teelahti if you have a change, could you test the dev branch on your env to see if the issue still reproduces? You can install the dev branch manually by ssh'ing into Home Assistant (I'm quite certain you already know this stuff though..)
> 
> Done, and HA restarted after. I'll report back tomorrow.

Thanks, even though upcoming night will most probably still fail as next night is already locked in using old version.
However, I'm 90% certain the fix will work as I managed to reproduce it with tests 🙂

**Comment by teelahti** [comment]
You were right. I'll double-check it works the upcoming night.

**Comment by teelahti** [comment]
Unfortunately it did not work. First time I checked in the morning it still had both List and ListNext, like the migration from one to another would not have happened. But now there's only List, and the state of the sensor never changed.

<img width="548" alt="Screenshot 2024-10-29 at 10 27 00" src="https://github.com/user-attachments/assets/68a4d131-9d38-4a20-b345-80886570a504">

Logs are full of the "No today fetch done..." rows until 22:00 UTC (00:00 local) when the sensor should have toggled on. At that point debug logging completely ended, and started again at 6:00 UTC with:

```text
2024-10-29 06:00:08.231 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No today fetch done for cheapest_electricity_hours or value is expired. Request new data from nord pool integration
2024-10-29 06:00:08.232 DEBUG (MainThread) [custom_components.aio_energy_management.coordinator] Request to save data: {'cheapest_electricity_hours': {'active_number_of_hours': 8, 'failsafe': {'start': datetime.time(0, 0), 'end': datetime.time(8, 0)}, 'expiration': datetime.datetime(2024, 10, 30, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'updated_at': datetime.datetime(2024, 10, 29, 8, 0, 8, 232244, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'fetch_date': datetime.date(2024, 10, 28), 'name': 'Cheapest electricity hours', 'type': 'CheapestHoursBinarySensor', 'list': [{'start': datetime.datetime(2024, 10, 29, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 29, 1, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}, {'start': datetime.datetime(2024, 10, 29, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 29, 3, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}, {'start': datetime.datetime(2024, 10, 29, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 10, 30, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}]}, 'cheapest_electricity_hours2': {'active_number_of_hours': 8, 'failsafe': {'start': '00:00:00', 'end': '08:00:00'}, 'list': [{'start': datetime.datetime(2024, 10, 27, 4, 0, tzinfo=UTC+02:00), 'end': datetime.datetime(2024, 10, 27, 11, 0, tzinfo=UTC+02:00)}, {'start': datetime.datetime(2024, 10, 27, 23, 0, tzinfo=UTC+02:00), 'end': datetime.datetime(2024, 10, 28, 0, 0, tzinfo=UTC+02:00)}], 'expiration': datetime.datetime(2024, 10, 28, 0, 0, tzinfo=UTC+02:00), 'updated_at': datetime.datetime(2024, 10, 27, 8, 0, 5, 277412, tzinfo=UTC+02:00), 'fetch_date': datetime.date(2024, 10, 27), 'name': 'Cheapest electricity hours2', 'type': 'CheapestHoursBinarySensor', 'list_next': [{'start': datetime.datetime(2024, 10, 28, 0, 0, tzinfo=UTC+02:00), 'end': datetime.datetime(2024, 10, 28, 8, 0, tzinfo=UTC+02:00)}], 'list_next_expiration': datetime.datetime(2024, 10, 29, 0, 0, tzinfo=UTC+02:00)}}
2024-10-29 06:00:08.238 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255
```

**Comment by kotope** [comment]
Ok, seems like this keeps getting even more mysterious.. the weird part is that the data starts flowing again at 06:00. There should be nothing related to that certain time on the AIO Energy Management integration or in your configuration what so ever.
I'll look into Nord Pool integration code itself to see if I can find anything from there that can cause the issue.

I will publish 0.3.1 version out today anyway as there are other improvements as well, but I'll add couple of more debug lines so we can see the flow even more detail during next days. ..Unless you are already tired of this and will throw the integration out of the window 😁 

Btw, have you tried the same configuration through entso-e integration?

**Comment by teelahti** [comment]
I'll keep observing how this behaves during the upcoming nights. Don't get me wrong, I've been super happy with the previous more verbose approach you wrote, and I'm confident this will work soon for me again, too. 

Let me know if there is something I could do tho help. 

I have not tried entso-e.

**Comment by kotope** [comment]
If you still had your debug logs enabled, did you happen to get this debug log at any point of time: **"Nord pool provided old data: Ignore"** ?

**Comment by teelahti** [comment]
Nope, that was never logged.  
I'll switch to the new version when you release it, restart, and enable debug logging afterward.

**Comment by kotope** [comment]
> Nope, that was never logged. I'll switch to the new version when you release it, restart, and enable debug logging afterward.

Ok, there goes my theory of Nord Pool providing old data after midnight 😀 

Anyhow, I'll add some more logging to key sections of the code before today's release. Hopefully you can keep your integration running with debug logging enabled. 
And ff you could then provide me updates with logs in next couple of days it would be great.

**Comment by kotope** [comment]
As the codes starts flowing again at 06:00, it could be that, for some reason, data expiration comparison goes wrong versus system time provided.
I'll add log lines there as well to log both expiration and local time. Maybe that will then lighten things up a bit.

**Comment by kotope** [comment]
0.3.1 is now out @teelahti .

Please update to latest using HACS and enable debug logs if not yet enabled.
Would be very interested to see the logs over next night.

Mostly this log line:
https://github.com/kotope/aio_energy_management/blob/0e5697ab2e0208b611905db0b920c4700d36535b/custom_components/aio_energy_management/cheapest_hours_binary_sensor.py#L275

**Comment by teelahti** [comment]
Sorry, I have not reported back since someone dug my internet cable broken and Nordpool integration hasn't worked since. Will report when system is back online.

**Comment by teelahti** [comment]
No dice. HA got back online before noon, and Nordpool values were retrieved normally. Last night at 23:00 UTC (1:00 local) sensor should have switched on. But logs say the sensor was running on failsafe at that moment (and through the night):

```text
2024-10-31 23:00:13.559 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Checking expiration. Expiration as local = 2024-11-01 00:00:00+02:00, now = 2024-11-01 01:00:13.559063+02:00
2024-10-31 23:00:13.559 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Running on failsafe: True
2024-10-31 23:00:13.559 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Failsafe on. Don't interrupt the operation.
2024-10-31 23:00:13.560 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Checking expiration. Expiration as local = 2024-11-01 00:00:00+02:00, now = 2024-11-01 01:00:13.560328+02:00
```

Then later at 6:00 UTC the failsafe ends and sensor refreshes back to working state:

```text
2024-11-01 05:59:44.415 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Running on failsafe: True
2024-11-01 06:00:14.415 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Checking expiration. Expiration as local = 2024-11-01 00:00:00+02:00, now = 2024-11-01 08:00:14.414935+02:00
2024-11-01 06:00:14.415 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Running on failsafe: False
2024-11-01 06:00:14.415 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No today fetch done for cheapest_electricity_hours or value is expired. Request new data from nord pool integration
2024-11-01 06:00:14.415 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Checking expiration. Expiration as local = 2024-11-01 00:00:00+02:00, now = 2024-11-01 08:00:14.415620+02:00
2024-11-01 06:00:14.415 DEBUG (MainThread) [custom_components.aio_energy_management.coordinator] Request to save data: {'cheapest_electricity_hours': {'active_number_of_hours': 8, 'failsafe': {'start': datetime.time(0, 0), 'end': datetime.time(8, 0)}, 'expiration': datetime.datetime(2024, 11, 2, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'updated_at': datetime.datetime(2024, 11, 1, 8, 0, 14, 415792, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'fetch_date': datetime.date(2024, 10, 31), 'name': 'Cheapest electricity hours', 'type': 'CheapestHoursBinarySensor', 'list': [{'start': datetime.datetime(2024, 11, 1, 1, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 11, 1, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}, {'start': datetime.datetime(2024, 11, 1, 21, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki')), 'end': datetime.datetime(2024, 11, 2, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/Helsinki'))}]}, 'cheapest_electricity_hours2': {'active_number_of_hours': 8, 'failsafe': {'start': '00:00:00', 'end': '08:00:00'}, 'list': [{'start': datetime.datetime(2024, 10, 27, 4, 0, tzinfo=UTC+02:00), 'end': datetime.datetime(2024, 10, 27, 11, 0, tzinfo=UTC+02:00)}, {'start': datetime.datetime(2024, 10, 27, 23, 0, tzinfo=UTC+02:00), 'end': datetime.datetime(2024, 10, 28, 0, 0, tzinfo=UTC+02:00)}], 'expiration': datetime.datetime(2024, 10, 28, 0, 0, tzinfo=UTC+02:00), 'updated_at': datetime.datetime(2024, 10, 27, 8, 0, 5, 277412, tzinfo=UTC+02:00), 'fetch_date': datetime.date(2024, 10, 27), 'name': 'Cheapest electricity hours2', 'type': 'CheapestHoursBinarySensor', 'list_next': [{'start': datetime.datetime(2024, 10, 28, 0, 0, tzinfo=UTC+02:00), 'end': datetime.datetime(2024, 10, 28, 8, 0, tzinfo=UTC+02:00)}], 'list_next_expiration': datetime.datetime(2024, 10, 29, 0, 0, tzinfo=UTC+02:00)}}
2024-11-01 06:00:14.420 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] No values for tomorrow_valid in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_0255 
2024-11-01 06:00:14.420 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Could not get the latest data from nordpool integration
2024-11-01 06:00:14.421 DEBUG (MainThread) [custom_components.aio_energy_management.cheapest_hours_binary_sensor] Checking expiration. Expiration as local = 2024-11-02 00:00:00+02:00, now = 2024-11-01 08:00:14.421179+02:00
```

Based on this I would guess toggling failsafe on and off is the culprit: it seems to be on even when it shouldn't, and during the failsafe period the sensor does not - by design - work.

**Comment by kotope** [comment]
Thanks @teelahti, I think now I got it.. 

Failsafe triggers before list swap is made as failsafe_starting_hour and start_time are the same and once running on failsafe, we will ignore rest of the 'commands'. Indeed a bug.
You could set failsafe to start at 01:00 to overcome this issue until I manage to fix this. (Will be earliest next week as I'm going to have a little weekend off).

I most probably made some stupid mistake while testing your configuration on my env as it should reproduce 100% with this config. Will try again.

**Comment by teelahti** [comment]
Nice, that again makes sense, I'll try that tonight.

**Comment by teelahti** [comment]
You were right: changing failsafe to start at 1:00 fixed it 🙌🏽.

**Comment by kotope** [comment]
Thanks for verification! I'll try to find a permanent fix for this as soon as possible.
Also will change the bug title to indicate the root cause.

**Comment by kotope** [comment]
Verified and fixed on dev now. I will publish a new release this afternoon that finally fixes this issue.

**Comment by kotope** [comment]
Fix released with 0.3.2
